ALTER TABLE meal_entries ADD COLUMN IF NOT EXISTS protein NUMERIC(6, 2);
ALTER TABLE meal_entries ADD COLUMN IF NOT EXISTS carbs NUMERIC(6, 2);
ALTER TABLE meal_entries ADD COLUMN IF NOT EXISTS fat NUMERIC(6, 2);
ALTER TABLE meal_entries ADD COLUMN IF NOT EXISTS fiber NUMERIC(6, 2);
ALTER TABLE meal_entries ADD COLUMN IF NOT EXISTS sugar NUMERIC(6, 2);